version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8010:8010'
    volumes:
      - ./data:/app/data  # データ永続化用のマウントポイントを設定

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=ik